dist: trusty
sudo: false
language: generic
branches:
  only:
    - master
before_install:
  - wget https://repo.anaconda.com/miniconda/Miniconda3-py38_4.9.2-Linux-x86_64.sh
    --output-document miniconda.sh
  - bash miniconda.sh -b -u -p $HOME/miniconda
  - source $HOME/miniconda/etc/profile.d/conda.sh
  - hash -r
  - conda config
    --set always_yes yes
    --set changeps1 no
install:
  - conda env create --quiet --file build/environment.yml
  - conda list --name manubot
  - conda activate manubot
script:
  - sh build/build.sh
cache:
  directories:
    - ci/cache
after_success:
  - test $TRAVIS_BRANCH = "master" &&
    test $TRAVIS_EVENT_TYPE = "push" &&
    sh ci/deploy.sh
